#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MonoAndroidDemo.Resource", IsApplication=true)]

namespace MonoAndroidDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int fault_array = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int product_array = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int warranty_array = 2131034114;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int aztec = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int codabar = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int code_128 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int code_39 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int code_93 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int data_matrix = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ean_13 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ean_8 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int itf = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int pdf_417 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int qr_code = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int upc_a = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int upc_e = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int buttonDecoderAppSample = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int buttonDecoderChooseExisting = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int buttonDecoderTakeNew = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int buttonEncoderGenerate = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int buttonEncoderSaveBarcode = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int buttonLogin = 2131099661;
			
			// aapt resource value: 0x7f060017
			public const int buttonUpload = 2131099671;
			
			// aapt resource value: 0x7f060005
			public const int buttonskipScan = 2131099653;
			
			// aapt resource value: 0x7f060016
			public const int ddAreaOfFault = 2131099670;
			
			// aapt resource value: 0x7f060012
			public const int ddTypeOfWarranty = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int ddTypeofProduct = 2131099668;
			
			// aapt resource value: 0x7f060003
			public const int imageViewDecoderBarcode = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int imageViewEncoderBarcode = 2131099656;
			
			// aapt resource value: 0x7f060010
			public const int textDetails = 2131099664;
			
			// aapt resource value: 0x7f060006
			public const int textEncoderValue = 2131099654;
			
			// aapt resource value: 0x7f060015
			public const int textFault = 2131099669;
			
			// aapt resource value: 0x7f06000e
			public const int textLoginInfo = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int textLoginInfosubtext = 2131099663;
			
			// aapt resource value: 0x7f06000c
			public const int textPassword = 2131099660;
			
			// aapt resource value: 0x7f060013
			public const int textProduct = 2131099667;
			
			// aapt resource value: 0x7f060018
			public const int textUploadStatus = 2131099672;
			
			// aapt resource value: 0x7f06000b
			public const int textUsername = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int textViewDecoderResult = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int textViewEncoderMsg = 2131099658;
			
			// aapt resource value: 0x7f060011
			public const int textWarranty = 2131099665;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DecoderActivityLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EncoderActivityLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoginActivityLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int UnitInfoLayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int area_prompt = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int product_prompt = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int warranty_prompt = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
